# Decorators
WHITE = "#FFFFFF"
BLACK = "#000000"
OLIVE_GREEN = "#8A8A75"
CHARCOAL = "#3D3B3B"
GREEN = "#1CBA17"
LIGHT_GREEN = "#12ED0B"

# kordinat bikin window
START_WINDOW_X = 540
START_WINDOW_Y = 200

# besar window
MAX_WIDTH = 920
MAX_HEIGHT = 600

# TEST VALUE COMBO BOX
TEST_VALUES = ["BARANG 1 - 50ML - RP50.000", "BARANG 2 - 50ML - RP50.000", 
               "BARANG 3 - 50ML - RP50.000"]

# font config
FONT_TYPE = "Times New Roman"
FONT_SIZE = 12

# font button
FONT_BUTTON_SIZE = 20
FONT_BUTTON_TAMBAH_TEXT = "TAMBAH"
FONT_BUTTON_HAPUS_TEXT = "KURANG"


# canvas config
NON_BORDER_CANVAS = 0

# window canvas atas
TOP_CANVAS_HEIGHT = 100

# window canvas kanan
RIGHT_CANVAS_WIDTH = 460
RIGHT_CANVAS_HEIGHT = MAX_HEIGHT - TOP_CANVAS_HEIGHT

# window canvas kiri
LEFT_CANVAS_WIDTH = MAX_WIDTH - RIGHT_CANVAS_WIDTH
LEFT_CANVAS_HEIGHT = MAX_HEIGHT - TOP_CANVAS_HEIGHT

# Combo Box canvas kiri
START_X_COMBO_BOX = 20
START_Y_COMBO_BOX = 50
COMBO_BOX_CANVAS_KIRI_WIDTH = (LEFT_CANVAS_WIDTH - START_X_COMBO_BOX) - START_X_COMBO_BOX 

# Button Tambah Kiri
BUTTON_TAMBAH_HEIGHT = 40
BUTTON_TAMBAH_WIDTH = 150
START_X_BUTTON_TAMBAH = 20
START_Y_BUTTON_TAMBAH = 300

# Button Keluar 