# Color Decorators
WHITE = "#FFFFFF"
BLACK = "#000000"
OLIVE_GREEN = "#8A8A75"
CHARCOAL = "#3D3B3B"
GREEN = "#1CBA17"
LIGHT_GREEN = "#12ED0B"
RED = "#D30F0F"
DARK_RED = "#7F1A1A"
DARK_BLUE = "#170F81"
PINKISH = "#BD1F1F"


# Time config (seconds)
SLEEP_DURATION = 2

# kordinat bikin window
START_WINDOW_X = 340
START_WINDOW_Y = 100

# besar window
MAX_WIDTH = 920
MAX_HEIGHT = 450

# font config
FONT_TYPE = "Times New Roman"
FONT_SIZE = 12

# font button
FONT_BUTTON_SIZE = 12
BUTTON_HEIGHT = 40
BUTTON_WIDTH = 125
ANCHOR_CENTER = "center"
CURSOR_HAND = "hand2"
NON_BORDER = 0

# canvas config
NON_BORDER_CANVAS = 0

# window canvas atas
TOP_CANVAS_HEIGHT = 75

# footer canvas
BOTTOM_CANVAS_HEIGHT = 25

# window canvas kanan
RIGHT_CANVAS_WIDTH = 460
RIGHT_CANVAS_HEIGHT = MAX_HEIGHT - TOP_CANVAS_HEIGHT

# window canvas kiri
LEFT_CANVAS_WIDTH = MAX_WIDTH - RIGHT_CANVAS_WIDTH
LEFT_CANVAS_HEIGHT = MAX_HEIGHT - TOP_CANVAS_HEIGHT

# Img Logo window
START_X_LOGO = MAX_WIDTH - 90
START_Y_LOGO = TOP_CANVAS_HEIGHT - 67
MAX_WIDTH_LOGO = MAX_WIDTH - 850
MAX_HEIGHT_LOGO = int(TOP_CANVAS_HEIGHT - 25) 

# Combo Box canvas kiri
START_X_COMBO_BOX = 20
START_Y_COMBO_BOX = 50
COMBO_BOX_CANVAS_KIRI_WIDTH = (LEFT_CANVAS_WIDTH - START_X_COMBO_BOX) - START_X_COMBO_BOX 

# Button Tambah Kiri
START_X_BUTTON_TAMBAH = 20
START_Y_BUTTON_TAMBAH = 270
FONT_BUTTON_TAMBAH_TEXT = "TAMBAH"

# Button Hapus Kanan 
START_X_BUTTON_HAPUS = 20
START_Y_BUTTON_HAPUS = START_Y_BUTTON_TAMBAH
FONT_BUTTON_HAPUS_TEXT = "HAPUS"

# Button Keluar Atas
FONT_BUTTON_KELUAR_TEXT = "EXIT"
START_X_BUTTON_KELUAR = 5
START_Y_BUTTON_KELUAR = TOP_CANVAS_HEIGHT - 70
BUTTON_KELUAR_ATAS_WIDTH = BUTTON_WIDTH - 75
BUTTON_KELUAR_ATAS_HEIGHT = BUTTON_HEIGHT - 10

# Button Pembayaran Kanan
START_X_BUTTON_PEMBAYARAN = (START_X_BUTTON_HAPUS + BUTTON_WIDTH) + START_X_BUTTON_HAPUS
START_Y_BUTTON_PEMBAYARAN = START_Y_BUTTON_HAPUS
FONT_BUTTON_PEMBAYARAN_TEXT = "PEMBAYARAN"

# Button Reset Kanan
START_X_BUTTON_RESET = BUTTON_WIDTH + START_X_BUTTON_PEMBAYARAN + START_X_BUTTON_HAPUS
START_Y_BUTTON_RESET = START_Y_BUTTON_HAPUS
FONT_BUTTON_RESET_TEXT = "RESET"

# Entry Box canvas kiri
START_X_ENTRY_BOX = 20
START_Y_ENTRY_BOX = START_Y_BUTTON_TAMBAH - 50
ENTRY_BOX_CANVAS_KIRI_WIDTH = (LEFT_CANVAS_WIDTH - START_X_ENTRY_BOX) - START_X_ENTRY_BOX 

# Label total
START_X_LABEL_TOTAL = START_X_BUTTON_HAPUS
START_Y_LABEL_TOTAL = START_Y_BUTTON_HAPUS - 40

# List box canvas kanan
START_X_FRAME_CANVAS_KANAN = START_X_BUTTON_HAPUS
START_Y_FRAME_CANVAS_KANAN = START_Y_LABEL_TOTAL - 160
FRAME_CANVAS_KANAN_WIDTH = 420 - START_X_FRAME_CANVAS_KANAN
FRAME_CANVAS_KANAN_HEIGHT = 150

# Label nama barang 
NAMA_BARANG_MSG = "Pilih produk : "
START_X_NAMA_BARANG = START_X_COMBO_BOX
START_Y_NAMA_BARANG = START_Y_COMBO_BOX - 30

# label input jumlah
JUMLAH_BARANG_MSG = "Input Jumlah Barang : "
START_X_INPUT_JUMLAH = START_X_ENTRY_BOX
START_Y_INPUT_JUMLAH = START_Y_ENTRY_BOX - 30

# label footer tanggal
START_X_LABEL_TANGGAL = MAX_WIDTH - 250
START_Y_LABEL_TANGGAL = 2

# Label footer waktu
START_X_LABEL_WAKTU = START_X_LABEL_TANGGAL + 150
START_Y_LABEL_WAKTU = START_Y_LABEL_TANGGAL

# Error Message
ERROR_MSG_DUPLIKAT = "Sudah ada barang dalam pesanan dan jumlahnya sama "
ERROR_MSG_PENAMBAHAN = "Masukkan Bilangan Valid!!"
ERROR_MSG_PENGHAPUSAN = "Masukkan Barang yang ingin dihapus"
ERROR_MSG_PEMBAYARAN_TIDAK_MENCUKUPI = "Uang kurang! Total harus dibayar: Rp{total_akhir:,}"
ERROR_MSG_PEMBAYARAN_TIDAK_ADA_PESANAN = "Pesanan masih kosong!"
ERROR_MSG_RESET_TIDAK_ADA_DIHAPUS = "Tidak ada barang yang dihapus"

# Exit Message
EXIT_MSG = "Apakah Anda yakin ingin keluar?"
CONFIRM_MSG = "Bye - bye :("