


TEST_VALUES = ["BARANG 1 - 50ML - RP50.000", "BARANG 2 - 50ML - RP50.000", 
               "BARANG 3 - 50ML - RP50.000"]

# font config
FONT_TYPE = "Times New Roman"
FONT_SIZE = 12
FONT_FOREGROUND = "#000000"

# kordinat bikin window
START_WINDOW_X = 540
START_WINDOW_Y = 200

# besar window
MAX_WIDTH = 920
MAX_HEIGHT = 800

# window canvas atas
TOP_CANVAS_HEIGHT = 100

# window canvas kanan
RIGHT_CANVAS_WIDTH = 460
RIGHT_CANVAS_HEIGHT = MAX_HEIGHT - TOP_CANVAS_HEIGHT

# window canvas kiri
LEFT_CANVAS_WIDTH = MAX_WIDTH - RIGHT_CANVAS_WIDTH
LEFT_CANVAS_HEIGHT = MAX_HEIGHT - TOP_CANVAS_HEIGHT

# Combo Box canvas kiri
START_X_COMBO_BOX = 20
START_Y_COMBO_BOX = 50
COMBO_BOX_CANVAS_KIRI_WIDTH = (LEFT_CANVAS_WIDTH - START_X_COMBO_BOX) - START_X_COMBO_BOX 
