# Color Decorators
WHITE = "#FFFFFF"
BLACK = "#000000"
OLIVE_GREEN = "#8A8A75"
CHARCOAL = "#3D3B3B"
GREEN = "#1CBA17"
LIGHT_GREEN = "#12ED0B"
RED = "#D30F0F"
DARK_RED = "#7F1A1A"

# Time config (seconds)
SLEEP_DURATION = 2

# kordinat bikin window
START_WINDOW_X = 540
START_WINDOW_Y = 100

# besar window
MAX_WIDTH = 920
MAX_HEIGHT = 600

# TEST VALUE COMBO BOX
TEST_VALUES = ["BARANG 1 - 50ML - RP50.000", "BARANG 2 - 50ML - RP50.000", 
               "BARANG 3 - 50ML - RP50.000"]

# font config
FONT_TYPE = "Times New Roman"
FONT_SIZE = 12

# font button
FONT_BUTTON_SIZE = 20
BUTTON_HEIGHT = 40
BUTTON_WIDTH = 150
ANCHOR_CENTER = "center"
CURSOR_HAND = "hand2"
NON_BORDER = 0

# canvas config
NON_BORDER_CANVAS = 0

# window canvas atas
TOP_CANVAS_HEIGHT = 100

# window canvas kanan
RIGHT_CANVAS_WIDTH = 460
RIGHT_CANVAS_HEIGHT = MAX_HEIGHT - TOP_CANVAS_HEIGHT

# window canvas kiri
LEFT_CANVAS_WIDTH = MAX_WIDTH - RIGHT_CANVAS_WIDTH
LEFT_CANVAS_HEIGHT = MAX_HEIGHT - TOP_CANVAS_HEIGHT

# Combo Box canvas kiri
START_X_COMBO_BOX = 20
START_Y_COMBO_BOX = 50
COMBO_BOX_CANVAS_KIRI_WIDTH = (LEFT_CANVAS_WIDTH - START_X_COMBO_BOX) - START_X_COMBO_BOX 

# Button Tambah Kiri
START_X_BUTTON_TAMBAH = 20
START_Y_BUTTON_TAMBAH = 300
FONT_BUTTON_TAMBAH_TEXT = "TAMBAH"

# Button Hapus Kanan 
START_X_BUTTON_HAPUS = 20
START_Y_BUTTON_HAPUS = 300
FONT_BUTTON_HAPUS_TEXT = "HAPUS"

# Button Keluar Atas
START_X_BUTTON_KELUAR = 20
START_Y_BUTTON_KELUAR = TOP_CANVAS_HEIGHT - 75
FONT_BUTTON_KELUAR_TEXT = "EXIT"

# Entry Box canvas kiri
START_X_ENTRY_BOX = 20
START_Y_ENTRY_BOX = START_Y_BUTTON_TAMBAH - 50
ENTRY_BOX_CANVAS_KIRI_WIDTH = (LEFT_CANVAS_WIDTH - START_X_ENTRY_BOX) - START_X_ENTRY_BOX 

# List box canvas kanan
START_X_LIST_BOX_CANVAS_KANAN = 20
START_Y_LIST_BOX_CANVAS_KIRI = 50
LIST_BOX_CANVAS_KANAN_WIDTH = (RIGHT_CANVAS_WIDTH - START_X_LIST_BOX_CANVAS_KANAN) - START_X_LIST_BOX_CANVAS_KANAN

# Error Message
ERROR_MSG_PENAMBAHAN = "Masukkan Bilangan Valid!!"
ERROR_MSG_PENGHAPUSAN = "Masukkan Barang yang ingin dihapus"

# Exit Message
EXIT_MSG = "Apakah Anda yakin ingin keluar?"
CONFIRM_MSG = "Bye - bye :("